[package]
name = "crawler"
version = "0.1.0"
authors = ["Hideyuki Tanaka <tanaka.hideyuki@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
argopt = "0.1"
easy-scraper = "0.2"
log = "0.4"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
ureq = "1.4"
